allowBuilds:
  "@vscode/vsce-sign": true
  keytar: true

engineStrict: true

minimumReleaseAge: 10080

minimumReleaseAgeExclude:

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@5.7.2

overrides:
  "@types/node": "^24.0.0"
  "@types/vscode": "1.74.0"
  "typescript": "^6.0.3"

verifyDepsBeforeRun: false
