name: Test

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        vscode: [ '1.74.0', 'stable', 'insiders' ]
        exclude:
          - os: macos-latest
            vscode: '1.74.0'
          - os: macos-latest
            vscode: 'insiders'
          - os: windows-latest
            vscode: '1.74.0'
          - os: windows-latest
            vscode: 'insiders'

    name: ${{ matrix.vscode }} on ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn

      - name: Run test suite
        if: runner.os == 'Linux'
        run: xvfb-run -a yarn run test
        env:
          CODE_VERSION: ${{ matrix.vscode }}

      - name: Run test suite
        if: runner.os != 'Linux'
        run: yarn run test
        env:
          CODE_VERSION: ${{ matrix.vscode }}

      - name: Generate coverage reports
        if: runner.os == 'Linux' && matrix.vscode == 'stable'
        run: xvfb-run -a yarn run coverage
        env:
          CODE_VERSION: 'stable'

      - name: Upload coverage reports to Codecov
        if: runner.os == 'Linux' && matrix.vscode == 'stable'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: false
