name: Test

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        vscode: [
          '1.74.0',
          'stable'
        ]

    name: ${{ matrix.vscode }} on ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn

      - name: Run test suite (${{ runner.os }})
        run: xvfb-run -a yarn run coverage
        env:
          CODE_VERSION: ${{ matrix.vscode }}
        if: runner.os == 'Linux'

      - name: Run test suite (${{ runner.os }})
        run: yarn run coverage
        env:
          CODE_VERSION: ${{ matrix.vscode }}
        if: runner.os != 'Linux'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: false
